### ISSUE TITLE
目前发现两个bug

### ISSUE THREAD

**Issue by Lincope** [XilyFeAAAA/RIVEN#1]
1.设置界面大区显示错误 头像也是 还是作者的GitHub头像

2.生涯背景修改失效

客户端版本13.15
Windows 10 22H2

**Comment by XilyFeAAAA** [comment]
> 1.设置界面大区显示错误 头像也是 还是作者的GitHub头像
> 
> 2.生涯背景修改失效
> 
> 客户端版本13.15 Windows 10 22H2

设置界面是我的介绍会在下个版本修复。然后生涯背景修改，Lcuapi返回`Failed to update summoner profile`暂时不知道是什么原因
